pipeline:
  name: Dev-Automation-Pipeline
  identifier: DevAutomationPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: infraautomationdev
        build: <+input>
  stages:
    - stage:
        name: Build-Code
        identifier: BuildCode
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: infraautomationdev
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_Validation
                  identifier: Run_Validation
                  spec:
                    shell: Sh
                    command: echo "Harness & GitHub validated."
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: Harness-Docker
                harnessImageConnectorRef: account.harnessImage
                os: MacOS
    - parallel:
        - stage:
            name: AWS-Deploy
            identifier: AWSDeploy
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: Terragrunt-Apply-AWS
                      identifier: TerragruntApplyAWS
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            delegateSelectors:
                              - docker-delegate
                            script: |-
                              cd aws
                              # Initialize using local config:
                              terragrunt init --terragrunt-config=terragrunt.local.hcl
                              # (optional) preview before apply:
                              terragrunt plan --terragrunt-config=terragrunt.local.hcl
                              # Apply into local terraform.tfstate
                              terragrunt apply --auto-approve --terragrunt-config=terragrunt.local.hcl
                        environmentVariables:
                          - name: AWS_ACCESS_KEY_ID
                            type: Secret
                            value: AWS_ACCESS_KEY_ID
                          - name: AWS_SECRET_ACCESS_KEY
                            type: Secret
                            value: AKIAURWV2XVECOD6Y7CS-skigit
                          - name: AWS_DEFAULT_REGION
                            type: String
                            value: us-east-1
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: Azure-Deploy
            identifier: AzureDeploy
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: Terragrunt-Apply-Azure
                      identifier: TerragruntApplyAzure
                      spec:
                        delegateSelectors:
                          - docker-delegate
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: |
                              # cd azure
                              # terragrunt init
                              # terragrunt apply --auto-approve

                              echo "Azure"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
