name: Deploy React App via SSH Deploy Key

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      # 1. Ensure git & unzip are available
      - name: Install Git & Unzip
        run: |
          if ! command -v git &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y git
          fi
          if ! command -v unzip &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y unzip
          fi

      # 2. Load your SSH deploy key into ssh-agent
      - name: Load SSH deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Trust GitHub’s host key so SSH clone doesn’t prompt
      - name: Add GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # 4. Clone your repo via SSH into the exact directory you'll use
      - name: Clone repository via SSH
        run: |
          rm -rf ~/infra-automation
          git clone https://github.com/nabeeldevxops06/infra-automation.git ~/infra-automation

    #   # 5. Unzip the application package inside that repo
    #   - name: Unzip application package
    #     run: |
    #       cd ~/infra-automation
    #       unzip digital-name-card-main.zip
    #       rm digital-name-card-main.zip

      # … previous steps …

        # 1. Install Node.js & npm globally 
      - name: Install Node.js & npm via NodeSource
        run: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -   # add NodeSource PPA :contentReference[oaicite:5]{index=5}
            sudo apt-get install -y nodejs                                     # installs /usr/bin/node & npm :contentReference[oaicite:6]{index=6}

        # 2. Globally install PM2 for all users
      - name: Install PM2 globally
        run: |
            sudo npm install -g pm2                                            # places pm2 in /usr/bin :contentReference[oaicite:7]{index=7}


      - name: Install dependencies & build
        run: |
          pwd
          ls -la
          cd /home/ubuntu/infra-automation/digital-name-card-main
          npm ci
          npm run build
  

      # 6. Serve with PM2 and configure auto-start
      - name: Serve & enable PM2 on boot
        run: |
          pm2 stop react-app || true
          pm2 serve build --name react-app --spa --port 3000               # serve build folder 
          pm2 save                                                         # snapshot the process list 
          sudo pm2 startup systemd -u ubuntu --hp /home/ubuntu             # generate and enable systemd unit :contentReference[oaicite:16]{index=16}
